### ISSUE TITLE
[Request feature] Copy QR Code image to clipboard

### ISSUE THREAD

**Issue by Iz-zzzzz** [monyxie/qr-lite#21]

**Comment by monyxie** [comment]
The QR code is rendered as a SVG image and Firefox doesn't provide a option to copy such image in the context menu. I think this makes sense.

**Comment by monyxie** [comment]
Feature is shipped in v2.8.0.

**Comment by Iz-zzzzz** [comment]
Thank you for implementing this feature 😀👍
