### ISSUE TITLE
Please add custom shortcut function

### ISSUE THREAD

**Issue by wakk121** [monyxie/qr-lite#22]
Currently you need to click the icon to use the QR code generation function, please add the customized shortcut key function

**Comment by monyxie** [comment]
Thanks for the proposal. Personally clicking the icon doesn't bother me that much but I suppose having the ability to assign a keyboard shortcut is indeed helpful for some people. I'll see what I can do.

**Comment by monyxie** [comment]
Starting in the next release, you will be able to set a custom shortcut for showing the popup in Firefox's "Manage Extension Shortcuts" page.
