### ISSUE TITLE
"Open link" does not work with links in all caps

### ISSUE THREAD

**Issue by iwconfig** [monyxie/qr-lite#26]
Howdy!

Self explanatory screenshots:

![Skärmklipp](https://github.com/monyxie/qr-lite/assets/10843441/da0924f1-8475-47d4-9d18-3763d187a97f)
![Skärmklipp2](https://github.com/monyxie/qr-lite/assets/10843441/028ba5de-ba11-4153-96b3-e578e785e354)

So basically, if the link is all caps, "Open links" button is not available. I assume this might be a regex issue.

Smell you later,
iwconfig

**Comment by iwconfig** [comment]
```diff
diff --git a/src/popup/popup.js b/src/popup/popup.js
index 33fec89..3d93c7c 100644
--- a/src/popup/popup.js
+++ b/src/popup/popup.js
@@ -169,7 +169,7 @@ class Popup {

         await that.addHistory('decode', text)

-        if (/^https?:\/\//.test(text)) {
+        if (/^https?:\/\//i.test(text)) {
           $openLinkBtn.classList.remove('hidden')
         }
       }
```

**Comment by monyxie** [comment]
Thank you for the bug report. It does seem to be a regex issue. I'll have a closer look.
